---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
platforms:
  # - name: bionic
  #   image: solita/ubuntu-systemd:18.04
  #   privileged: true
  #   command: /sbin/init
  - name: focal
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    # command: ${MOLECULE_DOCKER_COMMAND:-""}
    # volumes:
    #   - /sys/fs/cgroup:/sys/fs/cgroup:rw
    # cgroupns_mode: host
    # privileged: true
    # pre_build_image: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
