---
name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install pipenv
        run: pip3 install pipenv

      - name: Create pipenv
        run: pipenv install

      - name: Run Molecule tests
        run: pipenv run molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
